CREATE TABLE [dbo].[Developers]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[FirstName] NVARCHAR(50) NOT NULL,
	[LastName] NVARCHAR(50) NOT NULL,
	[Title] NVARCHAR(50) NULL,
	[City] NVARCHAR(50) NULL,
	[IsActive] bit NOT NULL)
